### ISSUE TITLE
Unexpected unit

### ISSUE THREAD

**Issue by margittennosaar** [preetiag18/TasteIt#3]
https://github.com/preetiag18/TasteIt/blob/f592cc0ad65896acf713ae426f53afb795f74b07/client/src/Addnewrecipe/Addnewrecipe.module.css#L30

When using 0 value in unit, keep it just **0** instead of **0px**

**Comment by preetiag18** [comment]
fixed this and one other place as well
https://github.com/preetiag18/TasteIt/commit/d72307d0b6deaaa2f714017f1b67957211bfb344#diff-f4cd07308c02973e8296047c6504a6ed3578f096f704acdc2b6909f1f748fb46R30
