### ISSUE TITLE
Unexpected vendor-prefix "-webkit-user-select"

### ISSUE THREAD

**Issue by margittennosaar** [preetiag18/TasteIt#4]
https://github.com/preetiag18/TasteIt/blob/f592cc0ad65896acf713ae426f53afb795f74b07/client/src/Hero/Hero.module.css#L50

user-select does not need vendor-prefix

**Comment by preetiag18** [comment]
removed this
https://github.com/preetiag18/TasteIt/commit/d72307d0b6deaaa2f714017f1b67957211bfb344#diff-9427adb65dfeb0e70d0ee734aa26d187a6b28a0fda150b746627c31aa3b7cc5aL50
