### ISSUE TITLE
circle() can not be empty

### ISSUE THREAD

**Issue by margittennosaar** [preetiag18/TasteIt#5]
https://github.com/preetiag18/TasteIt/blob/f592cc0ad65896acf713ae426f53afb795f74b07/client/src/SeeMoreRecipeDetails/SeeMoreRecipeDetails.module.css#L15

**Comment by preetiag18** [comment]
fixed it
https://github.com/preetiag18/TasteIt/commit/d72307d0b6deaaa2f714017f1b67957211bfb344#diff-4d3d369a1f9d8896d01a82524852312c69588f6d56704914cc498eb1edcfadccR15
